In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
import keras
from keras.models import Sequential
from keras.layers import Dense

In [11]:
dataset = pd.read_csv("/content/mnist_test.csv")
dataset.head(10)

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      7    0    0    0    0    0    0    0    0    0  ...    0.0    0.0   
1      2    0    0    0    0    0    0    0    0    0  ...    0.0    0.0   
2      1    0    0    0    0    0    0    0    0    0  ...    0.0    0.0   
3      0    0    0    0    0    0    0    0    0    0  ...    0.0    0.0   
4      4    0    0    0    0    0    0    0    0    0  ...    0.0    0.0   
5      1    0    0    0    0    0    0    0    0    0  ...    0.0    0.0   
6      4    0    0    0    0    0    0    0    0    0  ...    0.0    0.0   
7      9    0    0    0    0    0    0    0    0    0  ...    0.0    0.0   
8      5    0    0    0    0    0    0    0    0    0  ...    0.0    0.0   
9      9    0    0    0    0    0    0    0    0    0  ...    0.0    0.0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
5    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
6    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
7    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
8    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
9    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[10 rows x 785 columns]

In [12]:
dataset.describe()

label     1x1     1x2     1x3     1x4     1x5     1x6     1x7  \
count  6905.000000  6905.0  6905.0  6905.0  6905.0  6905.0  6905.0  6905.0   
mean      4.454164     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
std       2.893327     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
min       0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
25%       2.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
50%       4.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
75%       7.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
max       9.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

          1x8     1x9  ...        28x19        28x20        28x21  \
count  6905.0  6905.0  ...  6904.000000  6904.000000  6904.000000   
mean      0.0     0.0  ...     0.259705     0.236964     0.076188   
std       0.0     0.0  ...     6.827518     6.902314     2.912255   
min       0.0     0.0  ...     0.000000     0.000000     0.000000   
25%       0.0     0.0  ...     0.000000     0.000000     0.000000   
50%       0.0     0.0  ...     0.000000     0.000000     0.000000   
75%       0.0     0.0  ...     0.000000     0.000000     0.000000   
max       0.0     0.0  ...   253.000000   253.000000   156.000000   

             28x22   28x23   28x24   28x25   28x26   28x27   28x28  
count  6904.000000  6904.0  6904.0  6904.0  6904.0  6904.0  6904.0  
mean      0.000869     0.0     0.0     0.0     0.0     0.0     0.0  
std       0.072211     0.0     0.0     0.0     0.0     0.0     0.0  
min       0.000000     0.0     0.0     0.0     0.0     0.0     0.0  
25%       0.000000     0.0     0.0     0.0     0.0     0.0     0.0  
50%       0.000000     0.0     0.0     0.0     0.0     0.0     0.0  
75%       0.000000     0.0     0.0     0.0     0.0     0.0     0.0  
max       6.000000     0.0     0.0     0.0     0.0     0.0     0.0  

[8 rows x 785 columns]

In [13]:
dataset.dtypes

label      int64
1x1        int64
1x2        int64
1x3        int64
1x4        int64
          ...   
28x24    float64
28x25    float64
28x26    float64
28x27    float64
28x28    float64
Length: 785, dtype: object

In [14]:
X = dataset.iloc[:,:20].values
y = dataset.iloc[:,20:21].values

In [15]:
X

array([[7, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0],
       [8, 0, 0, ..., 0, 0, 0]])

In [16]:
y

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [17]:
# handling the features for NN model
sc = StandardScaler()
X = sc.fit_transform(X)

In [18]:
# handling the lable
ohe = OneHotEncoder()
y = ohe.fit_transform(y).toarray()
print(y)

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]


In [19]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 0.1, random_state=12)

In [20]:
model = Sequential()
model.add(Dense(units = 16,
activation='relu',
use_bias=True,
kernel_initializer="glorot_uniform",
bias_initializer="zeros",
kernel_regularizer=None,
bias_regularizer=None,
activity_regularizer=None,
kernel_constraint=None,
bias_constraint=None,
input_dim = 20))
model.add(Dense(units = 12,
activation='relu',
use_bias=True,
kernel_initializer="glorot_uniform",
bias_initializer="zeros",
kernel_regularizer=None,
bias_regularizer=None,
activity_regularizer=None,
kernel_constraint=None,
bias_constraint=None,
))
model.add(Dense(units = 4,
activation='softmax',
use_bias=True,
kernel_initializer="glorot_uniform",
bias_initializer="zeros",
kernel_regularizer=None,
bias_regularizer=None,
activity_regularizer=None,
kernel_constraint=None,
bias_constraint=None,
))

In [21]:
type(model)

keras.engine.sequential.Sequential

In [22]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'],loss_weights=None,
              weighted_metrics=None,run_eagerly=None,steps_per_execution=None,
              jit_compile=None)

In [23]:
type(model)

keras.engine.sequential.Sequential

In [24]:
y_pred = model.predict(X_test)

22/22 [==============================] - 0s 1ms/step


In [26]:
pred = list()
for var in range(len(y_pred)):
  pred.append(np.argmax(y_pred[var]))

In [27]:
test = list()
for var in range(len(y_test)):
  test.append(np.argmax(y_test[var]))

In [28]:
pred[0:10]

[0, 0, 0, 0, 0, 3, 3, 0, 3, 3]

In [29]:
test[0:10]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [30]:
from sklearn.metrics import accuracy_score
score = accuracy_score(pred,test)
print("Accurcy of the ANN Model is : ", score*100, "%")

Accurcy of the ANN Model is :  50.65123010130246 %
